# Welcome to Jekyll!
#

# Site settings
title: Sheffield Digital Leadership Meetup
description: |
  Leadership is not just for the CEO! Come and talk about how leadership works for you<br />
  whether you're a senior architect or a junior dev trying to change your team for the better.
owner: Sheffield Digital Leadership Meetup  # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sheffield-digital-leadership-meetup.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/sheffleadership
  #github: https://github.com/<username>
  # linkedin-square: https://linkedin.com/in/<username>
  # facebook-official: https://facebook.com/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  slack: https://sheffielddigital.slack.com/messages/CCFM9D5EK
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

# Collections
collections:
  - meetups
